<?php
use srag\Plugins\SrCrsLpReport\ReportTableGUI\AbstractReportTableGUI;

/**
 * Class SrCrsLpReportGUI
 *
 * Generated by srag\PluginGenerator v0.9.10
 *
 * @author            studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author            studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 *
 */

class HookilTrObjectUsersPropsTableGUI  extends AbstractReportTableGUI
{

	protected function initId() {
		$this->setId('srcrslp_usrs');
		$this->setPrefix('srcrslp_usrs');
	}
}
?>