<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

require_once __DIR__ . "/../../vendor/autoload.php";

use srag\Plugins\SrCrsLpReport\Utils\SrCrsLpReportTrait;
use srag\RemovePluginDataConfirm\SrCrsLpReport\AbstractRemovePluginDataConfirm;

/**
 * Class SrCrsLpReportRemoveDataConfirm
 *
 * Generated by srag\PluginGenerator v0.9.10
 *
 * @author            studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author            studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 *
 * @ilCtrl_isCalledBy SrCrsLpReportRemoveDataConfirm: ilUIPluginRouterGUI
 */
class SrCrsLpReportRemoveDataConfirm extends AbstractRemovePluginDataConfirm {

	use SrCrsLpReportTrait;
	const PLUGIN_CLASS_NAME = ilSrCrsLpReportPlugin::class;
}
