<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

namespace srag\Plugins\SrCrsLpReport\Config;

use srag\Plugins\SrCrsLpReport\Utils\SrCrsLpReportTrait;
use ilSrCrsLpReportPlugin;
use ilTextInputGUI;
use srag\ActiveRecordConfig\SrCrsLpReport\ActiveRecordConfigFormGUI;

/**
 * Class ConfigFormGUI
 *
 * Generated by srag\PluginGenerator v0.9.10
 *
 * @package srag\Plugins\SrCrsLpReport\Config
 *
 * @author  studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author  studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
class ConfigFormGUI extends ActiveRecordConfigFormGUI {

	use SrCrsLpReportTrait;
	const PLUGIN_CLASS_NAME = ilSrCrsLpReportPlugin::class;
	const CONFIG_CLASS_NAME = Config::class;


	/**
	 * @inheritdoc
	 */
	protected function initFields()/*: void*/ {
		$this->fields = [
			Config::KEY_CRS_REF_ID => [
				self::PROPERTY_CLASS => ilTextInputGUI::class,
				self::PROPERTY_REQUIRED => true
			]
		];
		// TODO: Implement ConfigFormGUI
	}
}
