<?php

/* Copyright (c) 1998-2009 ILIAS open source, Extended GPL, see https://github.com/ILIAS-eLearning/ILIAS/tree/trunk/docs/LICENSE */

namespace srag\Plugins\SrCrsLpReport\Config;

use srag\Plugins\SrCrsLpReport\Utils\SrCrsLpReportTrait;
use ilSrCrsLpReportPlugin;
use srag\ActiveRecordConfig\SrCrsLpReport\ActiveRecordConfig;

/**
 * Class Config
 *
 * Generated by srag\PluginGenerator v0.9.10
 *
 * @package srag\Plugins\SrCrsLpReport\Config
 *
 * @author  studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 * @author  studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
class Config extends ActiveRecordConfig {

	use SrCrsLpReportTrait;
	const TABLE_NAME = "ui_uihk_srcrslp_config";
	const PLUGIN_CLASS_NAME = ilSrCrsLpReportPlugin::class;
	const KEY_CRS_REF_ID = "crs_ref_id";
	/**
	 * @var array
	 */
	protected static $fields = [
		self::KEY_CRS_REF_ID => self::TYPE_INTEGER
	];
	// TODO: Implement Config
}
