<?php

namespace srag\Plugins\SrLpReport\Access;

use ilSrLpReportPlugin;
use srag\DIC\SrLpReport\DICTrait;
use srag\Plugins\SrLpReport\Report\ReportInterface;
use srag\Plugins\SrLpReport\Utils\SrLpReportTrait;

/**
 * Class Ilias
 *
 * Generated by srag\PluginGenerator v0.9.10
 *
 * @package srag\Plugins\SrLpReport\Access
 *
 * @author  studer + raimann ag - Team Custom 1 <support-custom1@studer-raimann.ch>
 */
final class Ilias {

	use DICTrait;
	use SrLpReportTrait;
	const PLUGIN_CLASS_NAME = ilSrLpReportPlugin::class;
	/**
	 * @var self
	 */
	protected static $instance = NULL;


	/**
	 * @return self
	 */
	public static function getInstance(): self {
		if (self::$instance === NULL) {
			self::$instance = new self();
		}

		return self::$instance;
	}


	/**
	 * Ilias constructor
	 */
	private function __construct() {

	}


	/**
	 * @param int $obj_ref_id
	 * @param int $usr_id
	 * @param int $report_view_type
	 *
	 * @return ReportInterface
	 */
	public function reportRefIdUserId(int $obj_ref_id, int $usr_id, int $report_view_type): ReportInterface {
		return self::report()->buildReportRefIdUserId($obj_ref_id, $usr_id, $report_view_type);
	}
}
