<#1>
<?php
\srag\Plugins\SrLpReport\Config\Config::updateDB();
?>
<#2>
<?php
\srag\Plugins\SrLpReport\Comment\Comment\Comment::updateDB_();
?>
<#3>
<?php
\srag\Plugins\SrLpReport\Comment\Comment\Comment::updateDB_();
?>
